title: Internet Archive Upload Scheduler
description: Upload documents in batches on a scheduled basis to the Internet Archive.
instructions: ''
type: object
documents:
  - query
properties:
  batch_size:
    title: 'Batch size'
    type: integer
    default: 25
    description: "How many documents do you want upload to the Internet Archive per scheduled run?"
required:
  - batch_size
eventOptions:
  name: ia_upload_scheduler
  events:
    - hourly
    - daily
    - weekly
categories: 
  - export
version: 2
